/*
 * IB Connect
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarketCommentaryBodyRichText {
    #[serde(rename = "blocks")]
    pub blocks: Vec<models::Block>,
}

impl MarketCommentaryBodyRichText {
    pub fn new(blocks: Vec<models::Block>) -> MarketCommentaryBodyRichText {
        MarketCommentaryBodyRichText {
            blocks,
        }
    }
}

