/*
 * IB Connect
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarketCommentaryMetadataDefinitionsListedSecurity {
    /// Primary security FIGI identifier
    #[serde(rename = "figi")]
    pub figi: String,
}

impl MarketCommentaryMetadataDefinitionsListedSecurity {
    pub fn new(figi: String) -> MarketCommentaryMetadataDefinitionsListedSecurity {
        MarketCommentaryMetadataDefinitionsListedSecurity {
            figi,
        }
    }
}

