/*
 * IB Connect
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RetractSuggestionRecipientsInner {
    UserId(Box<models::UserId>),
}

impl Default for RetractSuggestionRecipientsInner {
    fn default() -> Self {
        Self::UserId(Default::default())
    }
}

