/*
 * IB Connect
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Room : An object containing information about an IB room.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Room {
    #[serde(rename = "roomId")]
    pub room_id: String,
}

impl Room {
    /// An object containing information about an IB room.
    pub fn new(room_id: String) -> Room {
        Room {
            room_id,
        }
    }
}

